# Generated by Django 5.2.3 on 2025-11-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia')], default='Efectivo', max_length=50)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('pendiente', 'Pendiente'), ('fallido', 'Fallido')], default='exitoso', max_length=20)),
            ],
        ),
    ]
